### ISSUE TITLE
anbox-modules-dkms-git is broken

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/repo#628]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* anbox-git (split: anbox-modules-dkms-git)

----

```
$ sudo modprobe ashmem_linux
modprobe: ERROR: could not insert 'ashmem_linux': Unknown symbol in module, or unknown parameter (see dmesg)
$ dmesg|tail -n2
[ 1107.931777] ashmem_linux: Unknown symbol __vfs_read (err 0)
[ 1111.761120] ashmem_linux: Unknown symbol __vfs_read (err 0)
```

**Comment by lilydjwg** [comment]
「受影响的软件包」那里得写包基础，不然 lilac 不认识（然后空格，后边你想写什么都行）。（不过你已经自己给指派好维护者、不用 lilac 操心了。）

**Comment by heavysink** [comment]
upstream出了挺多问题的，现在在等上游修改...

**Comment by heavysink** [comment]
@zsrkmyn 现在可以用了吗？

**Comment by zsrkmyn** [comment]
暂时没空测试😅

2018年1月24日 10:12，"巨型沉箱" <notifications@github.com>写道：

**Comment by zsrkmyn** [comment]
看起来不行 :-(

```
$ sudo pacman -S anbox-git anbox-image anbox-modules-dkms-git --asdeps
......
(1/3) Install DKMS modules
==> dkms install anbox-modules-ashmem/r717.b21e5d9 -k 4.15.5-1-ARCH
==> dkms install anbox-modules-binder/r717.b21e5d9 -k 4.15.5-1-ARCH
Error! Bad return status for module build on kernel: 4.15.5-1-ARCH (x86_64)
Consult /var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/make.log for more information.
(2/3) Arming ConditionNeedsUpdate...
(3/3) Updating the desktop file MIME type cache...
$ cat /var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/make.log
DKMS make.log for anbox-modules-binder-r717.b21e5d9 for kernel 4.15.5-1-ARCH (x86_64)
Sun Mar  4 16:04:12 CST 2018
make -C /lib/modules/4.15.5-1-ARCH/build V=0 M=$PWD
make[1]: Entering directory '/usr/lib/modules/4.15.5-1-ARCH/build'
  CC [M]  /var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/deps.o
  CC [M]  /var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/binder.o
In file included from ./include/linux/module.h:18:0,
                 from /var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/binder.c:29:
/var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/binder.c:149:39: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
 module_param_call(stop_on_user_error, binder_set_stop_on_user_error,
                                       ^
./include/linux/moduleparam.h:233:24: note: in definition of macro ‘module_param_call’
   { .flags = 0, .set = _set, .get = _get };  \
                        ^~~~
/var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/binder.c:149:39: note: (near initialization for ‘__param_ops_stop_on_user_error.set’)
 module_param_call(stop_on_user_error, binder_set_stop_on_user_error,
                                       ^
./include/linux/moduleparam.h:233:24: note: in definition of macro ‘module_param_call’
   { .flags = 0, .set = _set, .get = _get };  \
                        ^~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:316: /var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build/binder.o] Error 1
make[1]: *** [Makefile:1510: _module_/var/lib/dkms/anbox-modules-binder/r717.b21e5d9/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.15.5-1-ARCH/build'
make: *** [Makefile:8: all] Error 2
```

**Comment by heavysink** [comment]
日了🐶了...内核一升级又得重来...

**Comment by heavysink** [comment]
@zsrkmyn 你再试试看？

**Comment by zsrkmyn** [comment]
最近在编故事，没空测试 (laugh cry
等有空的时候大概有挂了吧2333

**Comment by heavysink** [comment]
@zsrkmyn 这波应该不会挂了...主要是dbus-cpp里面asio函数已经在boost lib中定义了...给dbus-cpp打了patch就好了。
